#define MAX_PRONOUN_PERSON  4
#define MAX_PRONOUN_GENDER  5
#define MAX_PRONOUN_TYPES   2
#define MAX_PRONOUN_PLURALS 2

const char PRONOUN_TABLE[MAX_PRONOUN_PERSON][MAX_PRONOUN_GENDER][MAX_PRONOUN_TYPES][MAX_PRONOUN_PLURALS][32];
